kind: pipeline
type: exec
name: win10

#platform:
#  os: windows
#  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
    - git config --global http.sslVerify false
    - git clone ${DRONE_GIT_HTTP_URL} .
    - git checkout ${DRONE_COMMIT}

- name: build pack
  commands:
    - chcp 65001
    - msbuild -t:restore
    - msbuild -t:build
  
- name: pack
  commands:
    - chcp 65001
    - msbuild -t:restore
    - msbuild -t:pack
  when:
   event:
    - tag